name: build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        config:
        - {
            name: Ubuntu_Latest_GCC,
            os: ubuntu-latest,
            compiler: g++
          }
        - {
            name: Ubuntu_Latest_Clang,
            os: ubuntu-latest,
            compiler: clang++
          }
        - {
            name: Ubuntu_18.04_GCC_4.8,
            os: ubuntu-18.04,
            compiler: g++-4.8
          }
        - {
            name: Ubuntu_18.04_CLang_4.0,
            os: ubuntu-18.04,
            compiler: clang++-4.0
          }
        # - {
        #     name: "MacOS_Latest_GCC",
        #     os: macos-latest,
        #     compiler: "g++"
        #   }
        # - {
        #     name: "MacOS_Latest_Clang",
        #     os: macos-latest,
        #     compiler: "clang"
        #   }
    
    name: ${{ matrix.config.name }}

    runs-on: ${{ matrix.config.os }}

    if: ${{ matrix.config.name == 'Ubuntu_18.04_GCC_4.8' }}
    uses: egor-tensin/setup-gcc@v1
    with:
      version: "4.8"
      platform: x64

    if: ${{ matrix.config.name == 'Ubuntu_18.04_CLang_4.0' }}
    uses: egor-tensin/setup-clang@v1
    with:
      version: "4.0"
      platform: x64

    steps:
      - uses: actions/checkout@v2

      - name: Configure CMake
        run: cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
        env:
          CXX: ${{ matrix.config.compiler }}

      - name: Build
        run: cmake --build ${{ github.workspace }}/build --config ${{ env.BUILD_TYPE }}

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: |
          bin/mapper --version
          bin/mapper_test
